//!!!!!!!!!! This file is generated automatically. To change it's contents, please change source file for auto generation. !!!!!!!
enum NodType {

BLANK = 0,
SC = 1,
EQ = 2,
LESS = 3,
GREATER = 4,
EQEQ = 5,
LESSEQ = 6,
GREATEREQ = 7,
PLUS = 8,
MINUS = 9,
MULT = 10,
DIV = 11,
RB = 12,
INT_CONST = 13,
DOUBLE_CONST = 14,
CHAR_CONST = 15,
STR_CONST = 16,
FUNC = 17,
INT = 18,
DOUBLE = 19,
CHAR = 20,
STR = 21,
LB = 22,
LFB = 23,
RFB = 24,
COMA = 25,
NOD_TYPE_CNT = 26
};